---
- name: Fail if 'role_nutanix_pe_register_pc_ip' is not defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_pe_register_pc_ip' is not defined."
  when:
    - role_nutanix_pe_register_pc_ip is not defined
    - role_nutanix_pe_register_pc_ip != ""

- name: Fail if 'role_nutanix_pe_register_pc_prism_central_username' is not defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_pe_register_pc_prism_central_username' is not defined."
  when:
    - role_nutanix_pe_register_pc_prism_central_username is not defined
    - role_nutanix_pe_register_pc_prism_central_username != ""

- name: Fail if 'role_nutanix_pe_register_pc_prism_central_password' is not defined
  ansible.builtin.fail:
    msg: "the variable 'role_nutanix_pe_register_pc_prism_central_password' is not defined."
  when:
    - role_nutanix_pe_register_pc_prism_central_password is not defined
    - role_nutanix_pe_register_pc_prism_central_password != ""
  no_log: true
