---
# tasks file for nutanix_role_prism_central_register_cluster
- name: Setup connection to Nutanix API
  ansible.builtin.include_role:
    name: grdavies.role_nutanix_prism_api
  vars:
    role_nutanix_prism_api_host: "{{ role_nutanix_pe_register_pc_host }}"
    role_nutanix_prism_api_host_username: "{{ role_nutanix_pe_register_pc_host_username }}"
    role_nutanix_prism_api_host_password: "{{ role_nutanix_pe_register_pc_host_password }}"
    role_nutanix_prism_api_host_port: "{{ role_nutanix_pe_register_pc_host_port }}"
    role_nutanix_prism_api_host_validate_certs: "{{ role_nutanix_pe_register_pc_host_validate_certs }}"
    role_nutanix_prism_api_debug: "{{ role_nutanix_pe_register_pc_debug }}"

- name: "Task can only be run against Prism Element"
  ansible.builtin.fail:
    msg: "'role_nutanix_pe_register_pc_host' needs to be set to the VIP of a Nutanix cluster. Please check the variable and try again."
  when:
    - role_nutanix_prism_api_endpoint_type != 'pe'

- name: Check variables
  ansible.builtin.import_tasks: check_variables.yml

- name: Register cluster
  ansible.builtin.import_tasks: register_cluster.yml

- name: Pause for 30 seconds to allow cluster registeration to finalize
  ansible.builtin.pause:
    seconds: 30
