---
- name: Get Prism Element registration state
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v1/multicluster/cluster_external_state"
    method: GET
    validate_certs: "{{ role_nutanix_pe_register_pc_host_validate_certs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
  register: role_nutanix_pe_register_pc_current_state
  no_log: true

- name: Debug role_nutanix_pe_register_pc_current_state
  ansible.builtin.debug:
    var: role_nutanix_pe_register_pc_current_state
  when: role_nutanix_pe_register_pc_debug

- name: " Register Nutanix PE to PC '{{ role_nutanix_pe_register_pc_ip }}'"
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v1/multicluster/add_to_multicluster"
    method: POST
    validate_certs: "{{ role_nutanix_pe_register_pc_host_validate_certs }}"
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    body_format: json
    body:
      ipAddresses: ["{{ role_nutanix_pe_register_pc_ip }}"]
      username: "{{ role_nutanix_pe_register_pc_username }}"
      password: "{{ role_nutanix_pe_register_pc_password }}"
      port: null
    status_code: 200
  register: role_nutanix_pe_register_pc_register
  no_log: true
  when: role_nutanix_pe_register_pc_current_state.json | length == 0

- name: Debug role_nutanix_pe_register_pc_register
  ansible.builtin.debug:
    var: role_nutanix_pe_register_pc_register
  when: role_nutanix_pe_register_pc_debug

- name: Cluster Prism Central registration failed
  ansible.builtin.fail:
    msg: "could not register cluster to prism central"
  when:
    - role_nutanix_pe_register_pc_current_state.json | length == 0
    - role_nutanix_pe_register_pc_register.failed
